
try{
    var n=5/0;
}
catch(err)
{
    console.log(err);
}
